# Scoring configuration
scoring:
  # Points for a job posting for a target persona with CDP keywords
  hiring_target_persona_with_cdp_keywords: 5
  
  # Points for an executive move into a target persona role
  executive_move_target_persona: 4
  
  # Points for explicitly naming a CDP vendor
  explicit_cdp_vendor_mention: 4
  
  # Points for mentions of unified data concepts
  unified_data_concepts: 3
  
  # Points for funding or expansion news
  funding_or_expansion: 2

# Keywords to look for in signals
keywords:
  # CDP vendor names
  cdp_vendors:
    - segment
    - mparticle
    - rudderstack
    - tealium
    - adobe real-time cdp
    - blueconic
    - lytics
    - treasure data
    - amperity
    - exponea
    - arm treasure data
    - salesforce cdp
    - oracle unity cdp
    - twilio segment
    - amplitude
    - mixpanel
    - braze
    - customer.io
    - iterable
    - hotjar
    - fullstory
    - heap
    - adevinta
    - hightouch

  # Target persona job titles - focused on CDP decision makers and implementers
  target_personas:
    # Executive roles (higher score)
    - chief marketing officer
    - chief data officer
    - chief digital officer
    - cto
    - vp marketing
    - vp data
    - vp analytics
    - vp engineering
    - vp product
    
    # Director-level roles (medium-high score)
    - director data platform
    - director of marketing technology
    - director of data
    - director of analytics
    - head of analytics
    - head of data
    - head of martech
    
    # Manager and specialist roles (medium score)
    - marketing technology manager
    - marketing operations manager
    - data engineering manager
    - analytics engineering manager
    - growth marketing manager
    
    # Technical implementers (medium-low score)
    - data engineer
    - analytics engineer
    - marketing data analyst
    - data scientist
    - marketing technology specialist
    - customer data architect

  # CDP-related concepts
  cdp_related:
    - customer data platform
    - cdp
    - data integration
    - customer 360
    - unified data
    - real-time personalization
    - data orchestration
    - customer journey
    - omnichannel
    - first-party data
    - customer identity
    - identity resolution
    - audience segmentation
    - data activation
    - unified customer profile
    - customer data infrastructure
    - audience targeting
    - user segmentation
    - data governance
    - predictive analytics
    - personalized experience
    - user behavior analysis
    - customer engagement
    - data modeling
    - zero copy architecture
    - customer profile
    - linked profiles
    - data standardization

  # Data technology keywords
  data_tech:
    - snowflake
    - dbt
    - fivetran
    - bigquery
    - redshift
    - databricks
    - data lakehouse
    - data warehouse
    - data mesh
    - event stream
    - kafka
    - data pipeline
    - airflow
    - reverse etl
    - etl pipeline
    - data transformation
    - data quality
    - predictive traits
    - machine learning models
    - real-time analytics
    - event tracking
    - zero copy

# API configuration
api:
  # SerpAPI settings
  serpapi:
    rate_limit: 5  # Requests per second
    backoff_factor: 1.5
    max_retries: 3
  
  # Google Custom Search API settings
  google_cse:
    rate_limit: 10  # Requests per minute (Google's free tier limit)
    backoff_factor: 2
    max_retries: 3

# Web scraping configuration
scraping:
  timeout: 10  # Seconds
  max_retries: 3
  headers:
    User-Agent: "CDP Signal Scanner/0.1.0 (research tool, support@example.com)"
