# Scoring configuration
scoring:
  # Points for a job posting for a target persona with CDP keywords
  hiring_target_persona_with_cdp_keywords: 5
  
  # Points for an executive move into a target persona role
  executive_move_target_persona: 4
  
  # Points for explicitly naming a CDP vendor
  explicit_cdp_vendor_mention: 4
  
  # Points for mentions of unified data concepts
  unified_data_concepts: 3
  
  # Points for funding or expansion news
  funding_or_expansion: 2

# Keywords to look for in signals
keywords:
  # CDP vendor names
  cdp_vendors:
    - segment
    - mparticle
    - rudderstack
    - tealium
    - adobe real-time cdp
    - blueconic
    - lytics
    - treasure data
    - amperity
    - exponea
    - arm treasure data
    - salesforce cdp
    - oracle unity cdp
    - twilio segment
    - amplitude
    - mixpanel
    - braze
    - customer.io
    - iterable
    - hotjar
    - fullstory
    - heap
    - adevinta
    - hightouch

  # Target persona job titles - focused on CDP decision makers and implementers
  target_personas:
    # Executive roles (higher score)
    - chief marketing officer
    - chief data officer
    - chief digital officer
    - cto
    - vp marketing
    - vp data
    - vp analytics
    - vp engineering
    - vp product
    
    # Director-level roles (medium-high score)
    - director data platform
    - director of marketing technology
    - director of data
    - director of analytics
    - head of analytics
    - head of data
    - head of martech
    
    # Manager and specialist roles (medium score)
    - marketing technology manager
    - marketing operations manager
    - data engineering manager
    - analytics engineering manager
    - growth marketing manager
    
    # Technical implementers (medium-low score)
    - data engineer
    - analytics engineer
    - marketing data analyst
    - data scientist
    - marketing technology specialist
    - customer data architect

  # CDP-related concepts - Enhanced with advanced concepts from industry resources
  cdp_related:
    # Core CDP Terminology
    - customer data platform
    - cdp
    - real-time cdp
    - enterprise cdp
    
    # Data Unification Concepts
    - unified data
    - unified customer profile
    - unified view of customer
    - single customer view
    - golden record
    - single source of truth
    - customer 360
    - 360-degree customer view
    - identity resolution
    - identity management
    - identity graph
    - profile unification
    - linked profiles
    
    # Data Collection & Integration
    - data integration
    - data ingestion
    - data orchestration
    - first-party data
    - zero-party data
    - second-party data
    - third-party data
    - data standardization
    - data normalization
    - event tracking
    - data pipelines
    - customer data infrastructure
    - data collection
    - data activation
    - data modeling
    - zero copy architecture
    
    # Customer Experience & Personalization
    - real-time personalization
    - customer journey
    - journey orchestration
    - omnichannel experience
    - omnichannel orchestration
    - cross-channel marketing
    - personalized experience
    - hyper-personalization
    - next best action
    - customer engagement
    - contextual interactions
    - behavior-based targeting
    
    # Analytics & Segmentation
    - audience segmentation
    - user segmentation
    - predictive analytics
    - behavioral analytics
    - predictive modeling
    - customer analytics
    - segment activation
    - audience targeting
    - prescriptive analytics
    - journey analytics
    - propensity modeling
    - user behavior analysis
    - real-time analytics
    - customer intelligence
    
    # Data Management & Governance
    - data governance
    - consent management
    - privacy by design
    - customer trust
    - data compliance
    - data lineage
    - GDPR compliance
    - CCPA compliance
    - data quality management

  # Data technology keywords
  data_tech:
    - snowflake
    - dbt
    - fivetran
    - bigquery
    - redshift
    - databricks
    - data lakehouse
    - data warehouse
    - data mesh
    - event stream
    - kafka
    - data pipeline
    - airflow
    - reverse etl
    - etl pipeline
    - data transformation
    - data quality
    - predictive traits
    - machine learning models
    - real-time analytics
    - event tracking
    - zero copy

# API configuration
api:
  # SerpAPI settings
  serpapi:
    rate_limit: 5  # Requests per second
    backoff_factor: 1.5
    max_retries: 3
  
  # Google Custom Search API settings
  google_cse:
    rate_limit: 10  # Requests per minute (Google's free tier limit)
    backoff_factor: 2
    max_retries: 3

# Web scraping configuration
scraping:
  timeout: 10  # Seconds
  max_retries: 3
  headers:
    User-Agent: "CDP Signal Scanner/0.1.0 (research tool, support@example.com)"
